### ISSUE TITLE
log transform of as.mcens 

### ISSUE THREAD

**Issue by jharcum** [USGS-R/smwrQW#16]
I've created an as.mcens object.  and the corresponding slots for interval and censor.codes makes sense to me. I take log(x), a lower limit of 0 converts to -Inf ; however, the censor.codes stays at 0 rather than switching to -1. Below is a sample script. what is my mistake?

> library(smwrQW)
> 
> # create a simple censored variable (as.mcens is from smwrQW)
> l <- c(0    ,   2,  3 ,    -Inf, 5,   2.5 )
> u <- c(10   ,   2,  Inf,   4   , Inf, 3   ) 
> 
> df <- data.frame( conc=as.mcens(l,u))
> 
> df <- data.frame(conc= df$conc, logconc = log(df$conc))
> 
> df2 <- data.frame( cLow= df$conc@.Data[,1] , 
+                    cHi= df$conc@.Data[,2] ,
+                    cInt= df$conc@interval,
+                    cCode= df$conc@censor.codes,
+                    logcLow= df$logconc@.Data[,1] , 
+                    logcHi= df$logconc@.Data[,2] ,
+                    logcInt= df$logconc@interval,
+                    logcCode= df$logconc@censor.codes)
> df2
  cLow cHi  cInt cCode   logcLow    logcHi logcInt logcCode
1  0.0  10  TRUE     0      -Inf 2.3025851    TRUE        0
2  2.0   2 FALSE     0 0.6931472 0.6931472   FALSE        0
3  3.0 Inf FALSE     1 1.0986123       Inf   FALSE        1
4 -Inf   4 FALSE    -1      -Inf 1.3862944   FALSE       -1
5  5.0 Inf FALSE     1 1.6094379       Inf   FALSE        1
6  2.5   3  TRUE     0 0.9162907 1.0986123    TRUE        0

**Comment by dlorenz-usgs** [comment]
There is no mistake. The result is consistent--the original value was
interval censored and the transformed value is also interval censored, just
from -Inf to log(10). For any analysis, the difference is irrelevant--the
only difference would be in the computation of the log-likelihood values.

**Comment by jharcum** [comment]
But if I set original value is c(-Inf, 10) @interval is FALSE … so that led to my confusion why log c(-Inf, 10) would not also have @interval of FALSE.
