### ISSUE TITLE
all slots not returned for mcens object when using as.data.frame

### ISSUE THREAD

**Issue by jharcum** [USGS-R/smwrQW#17]
When as.data.frame is applied to an mcens object, all slots are not returned. Below i create a qw object (and apply as.data.frame) and get slots returned, then process is repeated with mcens, but as.data.frame does not return all slots (i.e., censor.code, interval, names). Please advise me how to correct my statement to get all slots for mcens object.

> # example from online 'as.double'
> Test1 <- as.qw(c(1,2,3,2,4,4), c("<", "<", "<", " ", " ", " "), "", NA_real_,
+                  "Miss", "None", "Mine", "TEST", "")
> 
> as.data.frame(Test1, expand=TRUE)
  Test1.va1 Test1.va2 Test1.rmk Test1.vqc Test1.rlv Test1.rmt Test1.unt Test1.mth Test1.nam Test1.pcd
1         0         1         <                  NA      Miss      None      Mine      TEST          
2         0         2         <                  NA      Miss      None      Mine      TEST          
3         0         3         <                  NA      Miss      None      Mine      TEST          
4         2         2                            NA      Miss      None      Mine      TEST          
5         4         4                            NA      Miss      None      Mine      TEST          
6         4         4                            NA      Miss      None      Mine      TEST          
> # -----< interval censored example >-----
> # lower and upper values
> l <- c(0    ,   2,  3 ,    -Inf, 5,   2.5 )
> u <- c(10   ,   2,  Inf,   4   , Inf, 3   )
> # create interval censored
> conc=as.mcens(l,u)
> # coerce to data frame
> as.data.frame(conc, expand=TRUE)
     conc
1  0 - 10
2       2
3      >3
4      <4
5      >5
6 2.5 - 3

**Comment by dlorenz-usgs** [comment]
The as.data.frame function for mcens only converts the data to a data frame
containing the data. There is no expand argument to convert it to anything
different.

**Comment by jharcum** [comment]
ok. got it.
