### ISSUE TITLE
as.qw-differences in values for remark.codes 

### ISSUE THREAD

**Issue by jharcum** [USGS-R/smwrQW#18]
I'm looking for advice on setting up left and interval censored data as qw objects. The vignette for creating qw object suggests using "I" for remark.codes to indicate interval censored data. In the below, I create some interval- and left-censored data with a couple of different strategies. I think i understand that for strictly left censored (i.e., 0-DL censored values) that using remark.codes ="<" is a convenient short cut rather than entering value2. However, I cannot see any particular value, or requirement to align the remark.codes with what is actually in values and value2.

Are there some particular advantages for how to set up less thans and interval censoring in qw using one approach or another (i.e., how is the best way to set up values, value2 and remark.code)?

(and a 2nd question, can you show me how to modify (or add rounding) to the below statement?)

> Test2 <- as.qw(values           = c(0,0,0,2,3,4), 
+                  remark.codes     = c("I", " ", "<", " ", "I", " "), 
+                  value.codes      = "", 
+                  reporting.level  = NA_real_,
+                  reporting.method = "Miss", 
+                  reporting.units  = "None", 
+                  analyte.method   = "Mine", 
+                  analyte.name     = "TEST",
+                  unique.code      = c("A","B","C","D","E","F"),
+                  value2           = c(1,2,2,2,4,4) )
Warning message:
In as.qw(values = c(0, 0, 0, 2, 3, 4), remark.codes = c("I", " ",  :
  Special remark.codes: I retained, but may require interpretation by the user.
> 
> as.data.frame(Test2, expand=TRUE)
  Test2.va1 Test2.va2 Test2.rmk Test2.vqc Test2.rlv Test2.rmt Test2.unt Test2.mth Test2.nam Test2.pcd
1         0         1         I                  NA      Miss      None      Mine      TEST         A
2         0         2                            NA      Miss      None      Mine      TEST         B
3         0         2         <                  NA      Miss      None      Mine      TEST         C
4         2         2                            NA      Miss      None      Mine      TEST         D
5         3         4         I                  NA      Miss      None      Mine      TEST         E
6         4         4                            NA      Miss      None      Mine      TEST         F

**Comment by dlorenz-usgs** [comment]
You can manually set the rounding slot.

**Comment by jharcum** [comment]
ok (I miss-interpreted the notes in ?as.qw. thanks.)
