### ISSUE TITLE
log transform class qw

### ISSUE THREAD

**Issue by jharcum** [USGS-R/smwrQW#19]
Q: Is it possible to coerce a log transform of a qw/left censoring data object to a qw/left (or mcens) censoring data object so that the new log transformed value can inherit the meta data from the original data and continue to have the .Data slots as lower and upper values?

In my investigation, I loaded a small data set (n=5) in below code chunk and create a multiply censored data object via as.mcens (df$conc_mcens) and as.qw (df$concQW). Computing the log of df$conc_mcens and df$concQW gives the same result (as I would expect). Then, I drop the last row of the data frame and df$concQW converts to a left-censored object (note that the last row of the data frame was ">3") so the change to a left-censored object is understandable. Now when I compute log, the output for df$concQW is "values" and "detlim" .... i guess that's because log(df$concQW) is an lcens object.

```
library(smwrQW)
options(stringsAsFactors = FALSE)
df <- data.frame( l = c( 0.224, 1.920, 0.000, 0.000, 3),
                  u = c( 0.224, 1.920, 0.007, 0.010, NA),
                  qualifier = c("", "", "<", "<", ">"))

df$conc_mcens <- as.mcens(df$l, df$u)

df$concQW <- as.qw(values           = df$l, 
                   value2           = df$u,
                   remark.codes     = df$qualifier,
                   value.codes      = "", 
                   reporting.level  = NA_real_, 
                   reporting.method = "", 
                   reporting.units  = "", 
                   analyte.method   = "", 
                   analyte.name     = "", 
                   unique.code      = "")  
df$concQW@rounding <-c(4,4)

# log transform trial 1
# both conc_mcens and concQW are 'multiple censoring'
# log of conc_mcens and log of concQW are the same
cbind(df$l, df$u, df$conc_mcens, log(df$conc_mcens))
cbind(df$l, df$u, df$concQW,     log(df$concQW))

# log transform trial 2
# drop last row, concQW converts to "left censoring"
# logs aren't the same 
df<-df[1:4,]
cbind(df$l, df$u, df$conc_mcens, log(df$conc_mcens))
cbind(df$l, df$u, df$concQW,     log(df$concQW))

```

**# log transform trial 1**
**# both conc_mcens and concQW are 'multiple censoring'**
**# log of conc_mcens and log of concQW are the same**

> cbind(df$l, df$u, df$conc_mcens, log(df$conc_mcens))
                 lower.val upper.val  lower.val  upper.val
[1,] 0.224 0.224     0.224     0.224 -1.4961092 -1.4961092
[2,] 1.920 1.920     1.920     1.920  0.6523252  0.6523252
[3,] 0.000 0.007     0.000     0.007       -Inf -4.9618451
[4,] 0.000 0.010     0.000     0.010       -Inf -4.6051702
[5,] 3.000    NA     3.000       Inf  1.0986123        Inf
> cbind(df$l, df$u, df$concQW,     log(df$concQW))
                 values value2  lower.val  upper.val
[1,] 0.224 0.224  0.224  0.224 -1.4961092 -1.4961092
[2,] 1.920 1.920  1.920  1.920  0.6523252  0.6523252
[3,] 0.000 0.007  0.000  0.007       -Inf -4.9618451
[4,] 0.000 0.010  0.000  0.010       -Inf -4.6051702
[5,] 3.000    NA  3.000    Inf  1.0986123        Inf

**> # log transform trial 2**
**> # drop last row, concQW converts to "left censoring"**
**> # logs aren't the same** 

> df<-df[1:4,]
> cbind(df$l, df$u, df$conc_mcens, log(df$conc_mcens))
                 lower.val upper.val  lower.val  upper.val
[1,] 0.224 0.224     0.224     0.224 -1.4961092 -1.4961092
[2,] 1.920 1.920     1.920     1.920  0.6523252  0.6523252
[3,] 0.000 0.007     0.000     0.007       -Inf -4.9618451
[4,] 0.000 0.010     0.000     0.010       -Inf -4.6051702
> cbind(df$l, df$u, df$concQW,     log(df$concQW))
                 values value2     values    detlim
[1,] 0.224 0.224  0.224  0.224 -1.4961092 -4.961845
[2,] 1.920 1.920  1.920  1.920  0.6523252 -4.961845
[3,] 0.000 0.007  0.000  0.007 -4.9618451 -4.961845
[4,] 0.000 0.010  0.000  0.010 -4.6051702 -4.605170

**Comment by dlorenz-usgs** [comment]
It is not possible to retain all of the meta data and log-transform data of
class "qw." The log transform converts the data to class "mcens."

Conceivably, that would be possible, but I decided that was not practical
for the first release version. There would be lots of ripple effects, more
than just log-transforming the reporting limit--the units would need to
indicate log-transform, the analytical method would be invalid, the
constituent would need to be modified and so forth. All that would be
necessary to provide check against some of the operations that assume a
lower limit of 0 (even for left-censored values) and fail on those
operations. So it was much easier to force the standard definition for
water-quality data.

You can manually extract the meta data you want to see from the "qw" data
object and even put it into a separate column if needed.

**Comment by jharcum** [comment]
ok. thanks for reply.
