### ISSUE TITLE
Plot model diagnostic 

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/smwrQW#2]
Could setGD be pulled out of the censReg summary plot function? I'd like to use setPDF and save a bunch of plots in a loop, but since it's hard-coded in there, that's not possible..I think.

**Comment by dlorenz-usgs** [comment]
All of the diagnostic plot functions have the set.up argument. If that is
set to FALSE, then you can use any plotting device that you have set up,
like setPDF. Am I missing something?

**Comment by ldecicco-USGS** [comment]
Ahhhh yeah. Sorry, I missed that.
