### ISSUE TITLE
https .gov changeover

### ISSUE THREAD

**Issue by wdwatkins** [USGS-R/smwrQW#21]
Found these lines with http .gov URLs using https://github.com/wdwatkins/gran_http_gov

HTTPS is supposed be available for everything by the end of December, but may not be yet.

Some of these URLs in .md and other documentation files won't show up on github unless you go to the raw file. Line numbers reference the number in the raw file when opened in a text editor, so the link may not point you to the right spot in some cases if lines are wrapping, etc.

- [x] https://github.com/USGS-R/smwrQW/blob/master/R/atrazine.spk.R#L7
- [x] https://github.com/USGS-R/smwrQW/blob/master/R/convert2qw.R#L27
- [x] https://github.com/USGS-R/smwrQW/blob/master/R/convertFqw.R#L17
- [x] https://github.com/USGS-R/smwrQW/blob/master/R/dlimit.R#L52
- [x] https://github.com/USGS-R/smwrQW/blob/master/R/importNWISqw.R#L59
- [x] https://github.com/USGS-R/smwrQW/blob/master/R/importQW.R#L46
- [x] https://github.com/USGS-R/smwrQW/blob/master/R/pcodeNWISqw.R#L21
- [x] https://github.com/USGS-R/smwrQW/blob/master/R/pcodeNWISqw.R#L60
- [x] https://github.com/USGS-R/smwrQW/blob/master/R/pcodeNWISqw.R#L78
- [ ] https://github.com/USGS-R/smwrQW/blob/master/R/readNWQLdl.R#L32
- [x] https://github.com/USGS-R/smwrQW/blob/master/README.md#L8
- [x] https://github.com/USGS-R/smwrQW/blob/master/README.md#L19
- [x] https://github.com/USGS-R/smwrQW/blob/master/inst/doc/QualityControl.Rnw#L331
- [x] https://github.com/USGS-R/smwrQW/blob/master/man/atrazine.spk.Rd#L49
- [x] https://github.com/USGS-R/smwrQW/blob/master/man/convert2qw.Rd#L49
- [x] https://github.com/USGS-R/smwrQW/blob/master/man/convertFqw.Rd#L41
- [x] https://github.com/USGS-R/smwrQW/blob/master/man/dlimit.Rd#L74
- [x] https://github.com/USGS-R/smwrQW/blob/master/man/importNWISqw.Rd#L85
- [x] https://github.com/USGS-R/smwrQW/blob/master/man/importQW.Rd#L89
- [x] https://github.com/USGS-R/smwrQW/blob/master/man/pcodeNWISqw.Rd#L47
- [x] https://github.com/USGS-R/smwrQW/blob/master/vignettes/QualityControl.Rnw#L331

**Comment by ldecicco-USGS** [comment]
https://nwql.cr.usgs.gov doesn't seem to be switched over yet.

**Comment by ldecicco-USGS** [comment]
still isn't ...closing the issue
