### ISSUE TITLE
Untangle qw-class from smwrQW

### ISSUE THREAD

**Issue by jharcum** [USGS-R/smwrQW#25]
I’ve been using smwrQW for handling censored data that I work with – primarily the qw class. 
 
My use is primarily for storing the data in a data frame, exploring the structure in the environment panel in Rstudio, using View, printing observations to the console, and writing to a csv file. (I would probably use rbindQW as well, but admit to not having seen that function till yesterday.) I'm not using any of the statistical features that smwr* provides at this time.
 
My dilemma is that I’m looking to get “my” package CRAN-ready, however, I cannot use packages that aren’t on the CRAN. So, I looked at bringing in the functions that you have in smwrQW (as.qw, qw-class, censor.R, show-censored, View.R and probably others). However, sifting through the functions and overlaps with lcens and mcens was becoming a heavy lift to figure out a focused extraction. 
 
So I was wondering you have a recommendation on a short list of the functions in smwrQW that would let me proceed with using your qw class?
 
Thank you in advance if this is something that you can provide insight on.

**Comment by jharcum** [comment]
I posted a question on stackoverflow on how to get non-CRAN packages [here](http://stackoverflow.com/questions/42819420/r-package-dependencies-not-installed-from-additional-repositories-revisited/42819887?noredirect=1#comment72753248_42819887). I got a response, and am working to implement it. I'll circle back to this issue thread if I can sort it out for my purpose.

**Comment by ldecicco-USGS** [comment]
Here's the list I could think of:

I'd start with including in your package:

https://github.com/USGS-R/smwrQW/blob/master/R/as.qw.R
https://github.com/USGS-R/smwrQW/blob/master/R/qw-class.R
https://github.com/USGS-R/smwrQW/blob/master/R/as.data.frame.R

And I think you'd *want*:
https://github.com/USGS-R/smwrQW/blob/master/R/View.r
https://github.com/USGS-R/smwrQW/blob/master/R/as.double.R
https://github.com/USGS-R/smwrQW/blob/master/R/convert2qw.R
https://github.com/USGS-R/smwrQW/blob/master/R/convertFqw.R
https://github.com/USGS-R/smwrQW/blob/master/R/format.R
https://github.com/USGS-R/smwrQW/blob/master/R/is.na.R
https://github.com/USGS-R/smwrQW/blob/master/R/rbindQW.R
https://github.com/USGS-R/smwrQW/blob/master/R/summary.R
https://github.com/USGS-R/smwrQW/blob/master/R/subset.R
https://github.com/USGS-R/smwrQW/blob/master/R/str.R

So probably the way I'd do it is just ploop those in your package, *don't* open smwrQW, and see how your normal workflow goes. There might be some other things I'm missing, so take special notice if something doesn't work.
