### ISSUE TITLE
Converting old datasets from USGSwsQW

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/smwrQW#3]
Any tips on the best way to convert a dataframe that has qw objects that was created with the `USGSwsQW` package? I un-installed `USGSwsQW` to see how `GSqwsr` did. Whenever I load an old dataset, it errors out:

```r
Loading required package: USGSwsQW
Error in .requirePackage(package) : 
  unable to find required package ‘USGSwsQW’
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘USGSwsQW’
```
So, I re-installed `USGSwsQW`, opened the data. Then made a script like this:

```r
QWindex <- as.numeric(which(sapply(QW, function(x) class(x)) == "qw"))
for (i in QWindex){
  attr(attr(QW[,i], "class"), "package") <- "smwrQW"
}
```
To convert all the classes.

Anyway, this works...I thought I'd put my solution out there. But, I'm not 100% certain there's not a more trivial way to do it. If so, I'd love to hear about it.

**Comment by dlorenz-usgs** [comment]
That would be about the only way that I know of. Or re-import the data
using the functions in smwrQW.

**Comment by ldecicco-USGS** [comment]
Yeah, we did enough cleaning of the data (removing blanks, QA, etc) that I didn't want to re-import if possible.
