### ISSUE TITLE
Is there a function for frequency of 'hits'?

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/smwrQW#4]
Say I have a column of lcens data. Is there a function or something trivial that will let me calculate the percentage of values that have no censoring (or even just pull out the indices of no censoring data)? I thought maybe as.numeric(x) might work (I expected NA's for the left-censored data, and numbers for the no censoring data).

**Comment by dlorenz-usgs** [comment]
Try pctCens.

**Comment by ldecicco-USGS** [comment]
That's what I need!
