### ISSUE TITLE
update install instructions in readme.md

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/smwrQW#6]
points to github install, which doesn't work for this package.

**Comment by dlorenz-usgs** [comment]
It was not changed the first time it was submitted to GRAN, so I forgot. I'll fix tomorrow.

**Comment by dlorenz-usgs** [comment]
Fixed and also found non fatal errors in the vignettes, which were fixed. new version soon.

**Comment by jread-usgs** [comment]
@dlorenz-usgs you want us to hold off on building the GRAN release?
