### ISSUE TITLE
Possible issue with number of predictors and censReg

### ISSUE THREAD

**Issue by scworland-usgs** [USGS-R/smwrQW#7]
There seems to be a bug associated with the number of predictors used in censReg. I am not fully up-to-speed on censored regression, so I may be overlooking something obvious. In my example below, the function works fine for 30 observations and 10 predictors, but returns zeros for the fitted values when using 30 observations and 11 predictors. This is meant to be a general case, and the number of predictors at which this error occurs is not a hard threshold. I looked for a functional relationship between the observations and predictors, but I could not find one.

```{r}
set.seed(5)
Y1 <- runif(30, 1, 10)

## 10 predictors
X1 <- data.frame(replicate(10, Y1 + rnorm(30)))

## 11 predictors
X2 <- data.frame(replicate(11, Y1 + rnorm(30)))

## make dataframes
D1 <- cbind(Y1,X1)
D2 <- cbind(Y1,X2)

## censored regression
fit.cens1 <- censReg(as.lcens(Y1, 5) ~ ., data=D1) 
fit.cens2 <- censReg(as.lcens(Y1, 5) ~ ., data=D2) 

## RMSE
rmse(fit.cens1)
[1] 0.5734079

rmse(fit.cens2)
[1] NA
```

**Comment by dlorenz-usgs** [comment]
There is an arbitrary limit of 25 explanatory variables. But in this case,
you have excessive censoring for the number of explanatory variables. Try
printing fit.cens2.

> fit.cens2
Call:
censReg(formula = as.lcens(Y1, 5) ~ ., data = D2)
Error in print.censReg(x) :
  Excessive censoring, fewer than 1.5 uncensored values for each parameter

The function censReg was designed not to fail, but print does, to
facilitate the complete execution of loops. I will insert a warning message
into the censReg function to indicate a non-zero return status.

**Comment by scworland-usgs** [comment]
Thank you, I will close the issue. 

Is the limit of 25 explanatory variables just something related to "best practice"? I originally noticed the 25 limit when running a preliminary analysis of 7Q10s and the gagesII dataset. 

I do have one other quick question, but I will open it as another issue so they will be separate.
