### ISSUE TITLE
Surv (ie...EGRET) data

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/smwrQW#8]
A nice add-on would be an extension to as.qw that converts surv data to a qw object, similar to:

https://github.com/USGS-R/rloadest/blob/master/R/loadReg.R#L178

Low priority...I may get to it eventually....

**Comment by dlorenz-usgs** [comment]
Yes, I've thought about it, but have not acted as it is a low priority. I'm
not sure that class "qw" is appropriate as there just not enough
information in a Surv object. output to class "lcens," "mcens," or simply
numeric would make the most sence.

**Comment by ldecicco-USGS** [comment]
The script I used was to take the average for any interval censored data, and then turn the rest of the data to lcens objects. So, that sounds pretty similar to what you are describing (?)

For example...
* left censored data coming in as (0.05 = concHigh, NA = concLow) would be "<0.05" 
* un-censored data coming is as (0.1 = concHigh, 0.1 = concLow) would be "0.1" 
* interval censored data coming in as (0.2 = concHigh, 0.1 = concLow) would be  "0.15"

**Comment by dlorenz-usgs** [comment]
That would be an approximation of interval-censored data for class lcens.
In general it is very good and shows very little difference in the analysis
from correctly reporting the data as interval, which would be possible for
class "mcens."

**Comment by ldecicco-USGS** [comment]
Doh! OK, I didn't read the mcens documentation. Much more appropriate.
