### ISSUE TITLE
lcens boxplots with no censoring

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/smwrQW#9]
I think that the lcens boxplots don't work if a group doesn't have any censored values:

```
test <- rnorm(75,mean = 1, sd = 1)
test[test < 0.05] <- 0.05
test <- as.lcens(test)
category <- c(rep("A",75))
boxPlot(test, group = category, Box = list(type = "tukey", censorstyle = "estimated"))

#Works if there are some censored values:
test <- rnorm(100,mean = 1, sd = 1)
test[test < 0.05] <- "<0.05"
test <- as.lcens(test)
category <- sample(c(rep("A",75),rep("B",25)))
boxPlot(test, group = category, Box = list(type = "tukey", censorstyle = "estimated"))


```

One work-around is to convert that particular group to numeric, but that becomes very cumbersome when there are mixed sample sizes.

**Comment by dlorenz-usgs** [comment]
Oops, fixed for data of class "qw" not "lcens." The error occurs if there
are no censored values for all groups and yaxis.log is set to TRUE
(default). The function boxPlotCensStats has been fixed to address the
problem. I'll up date the gitHub repository when I get back to the office.

The workaround is to add censorbox=0 to the Box list argument:


boxPlot(test, group=cat, Box = list(type = "tukey", censorstyle =
"estimated", censorbox=0))

**Comment by ldecicco-USGS** [comment]
FABULOUS! Thanks for saving me some work today!

**Comment by dlorenz-usgs** [comment]
If there are censored values, then you should not use censorbox=0 as it
overrides the observed censoring levels. At least that is the way it is
supposed to work.
